repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: &exclude_txtfiles >-
          (?x)^(
              tests/.*.*out|
              tests/.*.in|
              examples/.*.xsf|
              docs/.*.agr|
              docs/.*.xsf
          )$
      - id: fix-encoding-pragma
        args: ["--remove"]
        exclude: *exclude_txtfiles
      - id: mixed-line-ending
        exclude: *exclude_txtfiles
      - id: trailing-whitespace
        exclude: *exclude_txtfiles
      - id: check-json
      - id: check-yaml
      - id: check-toml

  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: "0.48"
  #   hooks:
  #     - id: check-manifest

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/ikamensh/flynt/
    rev: "0.76"
    hooks:
      - id: flynt
        args: ["--line-length=120", "--fail-on-change"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: &exclude_pyfiles >
          (?x)^(
              aiida_wannier90_workflows/utils/.*/predict_smooth_grid.py|
              aiida_wannier90_workflows/utils/.*/get_w90model_from_aiida.py|
              docs/.*|
              tests/.*(?<!\.py)$
          )$
        args: ["--ignore=D104,D202,D203,D213"]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.0-b1
    hooks:
      - id: pylint
        language: system
        exclude: *exclude_pyfiles
